RemoveTeam & RemoveChannel
JonasMuehlmann/BIB_VPR pull request #321
Opened 2021-08-16 13:28 UTC by LinusSteinert

# Related issues:

2021-08-16 13:54 UTC, JonasMuehlmann requested changes

2021-08-16 13:54 UTC, JonasMuehlmann commented on Messenger/Messenger.Core/Services/MessengerService.cs
>          /// <returns>True if the team was successfully deleted, false otherwise</returns>
Change return type in docstring.

2021-08-16 13:54 UTC, JonasMuehlmann commented on Messenger/Messenger.Core/Services/MessengerService.cs
>              logger.Information($"Return value: {result}");
Log `team` instead of `result`, when changing return type.

2021-08-16 13:54 UTC, JonasMuehlmann commented on Messenger/Messenger.Core/Services/MessengerService.cs
> +        public static async Task<Team> DeleteTeam(uint teamId)
You should not return without considering the value of `result` since you do not know if everything went fine.

2021-08-16 14:13 UTC, JonasMuehlmann commented on Messenger/Messenger.Core/Services/MessengerService.cs
>              logger.Information($"Return value: {result}");
Fixed in 09f420c.

2021-08-16 14:13 UTC, JonasMuehlmann commented on Messenger/Messenger.Core/Services/MessengerService.cs
> +        public static async Task<Team> DeleteTeam(uint teamId)
Fixed in 09f420c.

2021-08-16 14:13 UTC, JonasMuehlmann commented on Messenger/Messenger.Core/Services/MessengerService.cs
>          /// <returns>True if the team was successfully deleted, false otherwise</returns>
Fixed in 09f420c.

2021-08-16 14:25 UTC, JonasMuehlmann approved these changes

2021-08-16 14:28 UTC, JonasMuehlmann commented
@LinusSteinert You did not request anyones review, is this ready to merge? Also, did you change any settings in your editor? There were merge conflicts caused by invisible characters added to the files you edited...

2021-08-18 08:12 UTC, robbelDev approved these changes

2021-08-18 08:13 UTC, merged